[tool.poetry]
name = "verdict"
version = "0.1.0"
description = ""
authors = ["Abhinav Singh <abnvxsin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
pytz = "^2024.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
